//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAudioSession.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAudioOut {
            get {
                return ((string)(this["LastAudioOut"]));
            }
            set {
                this["LastAudioOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SizeAsWorkingArea {
            get {
                return ((bool)(this["SizeAsWorkingArea"]));
            }
            set {
                this["SizeAsWorkingArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorLabelsActive {
            get {
                return ((global::System.Drawing.Color)(this["ColorLabelsActive"]));
            }
            set {
                this["ColorLabelsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorLabelsHeaders {
            get {
                return ((global::System.Drawing.Color)(this["ColorLabelsHeaders"]));
            }
            set {
                this["ColorLabelsHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color ColorLabelsChanging {
            get {
                return ((global::System.Drawing.Color)(this["ColorLabelsChanging"]));
            }
            set {
                this["ColorLabelsChanging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorLabelsHigh {
            get {
                return ((global::System.Drawing.Color)(this["ColorLabelsHigh"]));
            }
            set {
                this["ColorLabelsHigh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorSoundWave {
            get {
                return ((global::System.Drawing.Color)(this["ColorSoundWave"]));
            }
            set {
                this["ColorSoundWave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorFreqPeakMeter {
            get {
                return ((global::System.Drawing.Color)(this["ColorFreqPeakMeter"]));
            }
            set {
                this["ColorFreqPeakMeter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29, 29, 29")]
        public global::System.Drawing.Color ColorBorders {
            get {
                return ((global::System.Drawing.Color)(this["ColorBorders"]));
            }
            set {
                this["ColorBorders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorBackground {
            get {
                return ((global::System.Drawing.Color)(this["ColorBackground"]));
            }
            set {
                this["ColorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TriggerFontInstallation {
            get {
                return ((bool)(this["TriggerFontInstallation"]));
            }
            set {
                this["TriggerFontInstallation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VFD Display")]
        public string FontVFD {
            get {
                return ((string)(this["FontVFD"]));
            }
            set {
                this["FontVFD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DSEG14 Classic")]
        public string FontNumeric {
            get {
                return ((string)(this["FontNumeric"]));
            }
            set {
                this["FontNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parsi")]
        public string FontHeaders {
            get {
                return ((string)(this["FontHeaders"]));
            }
            set {
                this["FontHeaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font bottons music")]
        public string FontPlaybackControls {
            get {
                return ((string)(this["FontPlaybackControls"]));
            }
            set {
                this["FontPlaybackControls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double FontVFDSize {
            get {
                return ((double)(this["FontVFDSize"]));
            }
            set {
                this["FontVFDSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double FontHeadersSize {
            get {
                return ((double)(this["FontHeadersSize"]));
            }
            set {
                this["FontHeadersSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal MorningHour {
            get {
                return ((decimal)(this["MorningHour"]));
            }
            set {
                this["MorningHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public decimal NightHour {
            get {
                return ((decimal)(this["NightHour"]));
            }
            set {
                this["NightHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public decimal DayDecibelThreshold {
            get {
                return ((decimal)(this["DayDecibelThreshold"]));
            }
            set {
                this["DayDecibelThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public decimal NightDecibelThreshold {
            get {
                return ((decimal)(this["NightDecibelThreshold"]));
            }
            set {
                this["NightDecibelThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal VolumeStep {
            get {
                return ((decimal)(this["VolumeStep"]));
            }
            set {
                this["VolumeStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SourceTitleAsChanging {
            get {
                return ((bool)(this["SourceTitleAsChanging"]));
            }
            set {
                this["SourceTitleAsChanging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorVolumePeakMeterLow {
            get {
                return ((global::System.Drawing.Color)(this["ColorVolumePeakMeterLow"]));
            }
            set {
                this["ColorVolumePeakMeterLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 168, 0")]
        public global::System.Drawing.Color ColorSpectrumAnalyser {
            get {
                return ((global::System.Drawing.Color)(this["ColorSpectrumAnalyser"]));
            }
            set {
                this["ColorSpectrumAnalyser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorSpectrumAnalyserHighPeaks {
            get {
                return ((global::System.Drawing.Color)(this["ColorSpectrumAnalyserHighPeaks"]));
            }
            set {
                this["ColorSpectrumAnalyserHighPeaks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColorVolumePeakMeterHigh {
            get {
                return ((global::System.Drawing.Color)(this["ColorVolumePeakMeterHigh"]));
            }
            set {
                this["ColorVolumePeakMeterHigh"] = value;
            }
        }
    }
}
